# Generated by Django 3.2.5 on 2021-08-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TATU', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Readers',
            new_name='Students',
        ),
    ]
