# Generated by Django 3.2.5 on 2021-08-13 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TATU', '0002_rename_readers_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('established_at', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Futbolchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(default=0)),
                ('salary', models.PositiveIntegerField(default=100)),
                ('klub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TATU.klub')),
            ],
        ),
    ]
