# Generated by Django 3.2.5 on 2021-08-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TATU', '0004_alter_futbolchi_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futbolchi',
            name='salary',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='klub',
            name='established_at',
            field=models.DateTimeField(),
        ),
    ]
